### ISSUE TITLE
DSM correctness

### ISSUE THREAD

**Issue by sabaka** [sevntu-checkstyle/dsm-maven-plugin#14]
Compare matrix with DSM from Sonar and check it correctness of dsm-maven.

**Comment by romani** [comment]
This image is uploaded just be referenced in README.md file
![screenshot-dsm-maven-plugin-in-package](https://cloud.githubusercontent.com/assets/812984/14018891/48d199ea-f18d-11e5-9504-7e5b9f20a7f4.png)
