### ISSUE TITLE
Check correctness of matrix

### ISSUE THREAD

**Issue by sabaka** [sevntu-checkstyle/dsm-maven-plugin#35]
As I remember we should have an article with comparing Sonar DSM and generated by this tool. I can remember I wrote it somewhere on github, but unfortunately I couldn't find it. @romani, is it possible the article is hidden? It should be on wiki..
Anyway, I don't remember results of correctness check. Should be checked and dtangler should be fixed if it's not correct.

**Comment by romani** [comment]
nothing is hidden. I do not remember such article at all.

**Comment by jimbethancourt** [comment]
@sabaka, if you find the article, please share it and I will try to address it.
